### ISSUE TITLE
Cert manager does not support release v1.27.1 of Kubernetes 

### ISSUE THREAD

**Issue by cyrilghali** [onedr0p/flux-cluster-template#714]
Hello,

According to [actual cert manager documentation](https://cert-manager.io/docs/installation/supported-releases/). Kubernetes `v1.27.1` is not supported.

![image](https://user-images.githubusercontent.com/40162921/235545869-261e8fb6-642f-44ba-8171-a038ec3322eb.png)

I think [this pr](https://github.com/onedr0p/flux-cluster-template/pull/710) should be reverted.

I'm using the latest release of `flux-cluster-template` (`v3.16.0`) 
I got an issue myself because cert-manager won't start.
Here is the output I got when doing `task cluster:resources`

```
task: [cluster:nodes] kubectl get nodes -o wide
NAME    STATUS   ROLES                       AGE   VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
k8s-1   Ready    control-plane,etcd,master   63m   v1.27.1+k3s1   192.168.1.151   <none>        Ubuntu 22.04.2 LTS   5.15.0-71-generic   containerd://1.6.19-k3s1
k8s-2   Ready    control-plane,etcd,master   62m   v1.27.1+k3s1   192.168.1.152   <none>        Ubuntu 22.04.2 LTS   5.15.0-71-generic   containerd://1.6.19-k3s1
k8s-3   Ready    control-plane,etcd,master   62m   v1.27.1+k3s1   192.168.1.153   <none>        Ubuntu 22.04.2 LTS   5.15.0-71-generic   containerd://1.6.19-k3s1
k8s-4   Ready    <none>                      62m   v1.27.1+k3s1   192.168.1.154   <none>        Ubuntu 22.04.2 LTS   5.15.0-71-generic   containerd://1.6.19-k3s1
task: [cluster:kustomizations] kubectl get kustomizations -A
NAMESPACE     NAME                                      AGE   READY   STATUS
flux-system   cluster                                   58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps                              58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-cert-manager                 58m   False   Health check failed after 3m0.029659391s: timeout waiting for: [HelmRelease/cert-manager/cert-manager status: 'InProgress']
flux-system   cluster-apps-cert-manager-issuers         58m   False   dependency 'flux-system/cluster-apps-cert-manager' is not ready
flux-system   cluster-apps-cloudflare-ddns              58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-echo-server                  58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-external-dns                 58m   False   Health check failed after 3m0.029307932s: timeout waiting for: [HelmRelease/networking/external-dns status: 'InProgress']
flux-system   cluster-apps-flux-webhooks                58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-hajimari                     58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-ingress-nginx                58m   False   dependency 'flux-system/cluster-apps-ingress-nginx-certificates' is not ready
flux-system   cluster-apps-ingress-nginx-certificates   58m   False   dependency 'flux-system/cluster-apps-cert-manager-issuers' is not ready
flux-system   cluster-apps-k8s-gateway                  58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-kube-vip                     58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-kubernetes-dashboard         58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-local-path-provisioner       58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-metallb                      58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-metallb-config               58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-metrics-server               58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-reloader                     58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   cluster-apps-weave-gitops                 58m   True    Applied revision: main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403
flux-system   flux                                      58m   True    Applied revision: v2.0.0-rc.1@sha256:c3c253bcbb928c64c519d26e39bbc57074eae7f6309bb901269bf1b3edc6574c
task: [cluster:helmreleases] kubectl get helmreleases -A
NAMESPACE      NAME                     AGE   READY   STATUS
cert-manager   cert-manager             58m   False   HelmChart 'flux-system/cert-manager-cert-manager' is not ready
default        echo-server              58m   True    Release reconciliation succeeded
default        hajimari                 57m   True    Release reconciliation succeeded
flux-system    weave-gitops             57m   True    Release reconciliation succeeded
kube-system    local-path-provisioner   57m   True    Release reconciliation succeeded
kube-system    metrics-server           57m   True    Release reconciliation succeeded
kube-system    reloader                 57m   True    Release reconciliation succeeded
monitoring     kubernetes-dashboard     57m   True    Release reconciliation succeeded
networking     cloudflare-ddns          58m   True    Release reconciliation succeeded
networking     external-dns             57m   False   HelmChart 'flux-system/networking-external-dns' is not ready
networking     k8s-gateway              56m   True    Release reconciliation succeeded
networking     metallb                  57m   True    Release reconciliation succeeded
task: [cluster:helmrepositories] kubectl get helmrepositories -A
NAMESPACE     NAME                   URL                                                AGE   READY   STATUS
flux-system   bitnami                https://charts.bitnami.com/bitnami                 58m   True    stored artifact: revision 'sha256:e09f8dfecb68411845ad6d79ef3243ae7edf930798531dd8004dad0895f04cf6'
flux-system   bjw-s                  https://bjw-s.github.io/helm-charts/               58m   True    stored artifact: revision 'sha256:630c2243ba75e98bab40b5e77df59e2e999f68b640e37a9e19e6688c1f3160d2'
flux-system   external-dns           https://kubernetes-sigs.github.io/external-dns     58m   True    stored artifact: revision 'sha256:1306bc29b2de1a874db51e3efdb1358ccd147835b9422201d2565e27f5a440d3'
flux-system   hajimari               https://hajimari.io                                58m   True    stored artifact: revision 'sha256:ba9498af5dcb01ce1ccfe5df0238497529fa84ea1ed9c53b4bdb9bb0d9db40fd'
flux-system   ingress-nginx          https://kubernetes.github.io/ingress-nginx         58m   True    stored artifact: revision 'sha256:2aae73323475f862170065e9fbd2a10925964bb9aed2aa78f6bc12569f2953dd'
flux-system   jetstack               https://charts.jetstack.io/                        58m   True    stored artifact: revision 'sha256:bbe9d3cccc2d30ee4f58ce8f7909ec648b9806e0fbd433615023761c74a96f6f'
flux-system   k8s-gateway            https://ori-edge.github.io/k8s_gateway/            58m   True    stored artifact: revision 'sha256:ce12759887329ca7c9d18e639187f2691849780900bd49c8d650dd12a5fb136b'
flux-system   kubernetes-dashboard   https://kubernetes.github.io/dashboard/            58m   True    stored artifact: revision 'sha256:de9f7e68ccfd6f98beb13808b4ea4586312ba9e71f8f6f3257d3fa2e2c14308d'
flux-system   metallb                https://metallb.github.io/metallb                  58m   True    stored artifact: revision 'sha256:434ae373a76e9a9a2804677f9e3e0f36f41043ad71756721ee9af945c810e906'
flux-system   metrics-server         https://kubernetes-sigs.github.io/metrics-server   58m   True    stored artifact: revision 'sha256:e9f523294955f69fa52b26770770ce9772d0e6c211d282233c87b02476787e6c'
flux-system   stakater               https://stakater.github.io/stakater-charts         58m   True    stored artifact: revision 'sha256:2b2629ed1a838efee2ac48ccdb761304ea0bf622fe060fd62e4c1b4b671a8717'
flux-system   weave-gitops           https://helm.gitops.weave.works                    58m   True    stored artifact: revision 'sha256:b3bd87b87b54bde315cc0205a517d8a6400a4e30071044784e5a11db29c33557'
task: [cluster:gitrepositories] kubectl get gitrepositories -A
NAMESPACE     NAME                     URL                                                 AGE   READY   STATUS
flux-system   home-kubernetes          https://github.com/cyrilghali/home-ops              58m   True    stored artifact for revision 'main@sha1:95ccb4ffd63ec71ea2922dac0a7fa26c7a060403'
flux-system   local-path-provisioner   https://github.com/rancher/local-path-provisioner   58m   True    stored artifact for revision 'v0.0.24@sha1:97e0501428f0a5bcac49ecd0bfdb051797c4a6c5'
task: [cluster:certificates] kubectl get certificates -A
error: the server doesn't have a resource type "certificates"
task: Failed to run task "cluster:resources": task: Failed to run task "cluster:certificates": exit status 1
task: Failed to run task "cluster:resources": task: Failed to run task "cluster:certificates": exit status 1```

**Comment by onedr0p** [comment]
Interestingly I upgraded from 1.26.4 to 1.27.1 without an issue. I'm curious about any more information you can find or provide. Maybe only fresh installs are affected :/

**Comment by cyrilghali** [comment]
Indeed, it's my first time using this template, and my machines are fresh install of Ubuntu 22.04.
I think I'm gonna test the previous release of this template and I'll let you know !

Running ```kubectl -n cert-manager describe hr cert-manager``` gave me the following events

``` 
Events:
  Type     Reason             Age    From                  Message
  ----     ------             ----   ----                  -------
  Warning  HealthCheckFailed  60m    kustomize-controller  Health check failed after 3m0.02700668s: timeout waiting for: [HelmRelease/cert-manager/cert-manager status: 'InProgress']
  Warning  HealthCheckFailed  56m    kustomize-controller  Health check failed after 3m0.028837988s: timeout waiting for: [HelmRelease/cert-manager/cert-manager status: 'InProgress']
  Warning  HealthCheckFailed  52m    kustomize-controller  Health check failed after 3m0.028696185s: 
....
  Warning  Progressing        29m    kustomize-controller  failed to update status, error: context canceled
....
  Warning  HealthCheckFailed  10m    kustomize-controller  Health check failed after 3m0.029659391s: timeout waiting for: [HelmRelease/cert-manager/cert-manager status: 'InProgress']
  Warning  HealthCheckFailed  6m25s  kustomize-controller  Health check failed after 3m0.026903284s: timeout waiting for: [HelmRelease/cert-manager/cert-manager status: 'InProgress']
  Warning  HealthCheckFailed  2m24s  kustomize-controller  Health check failed after 3m0.028983581s: timeout waiting for: [HelmRelease/cert-manager/cert-manager status: 'InProgress']```

and `kubectl -n flux-system describe hr cert-manager` give me the following event

```
Events:
  Type    Reason  Age   From             Message
  ----    ------  ----  ----             -------
  Normal  info    36m   helm-controller  HelmChart 'flux-system/cert-manager-cert-manager' is not ready
```

Also I did get an error on [my github actions](https://github.com/cyrilghali/home-ops/actions/runs/4855303653/jobs/8653718330), I don't know if I should have configured something / acces for flux? It might be unrelated to this issue.
![image](https://user-images.githubusercontent.com/40162921/235547823-86385713-5cfa-465a-ab97-1ea0bfacafce.png)

As I said, I'm gonna test the previous release and I'll let you know !

**Comment by onedr0p** [comment]
Do the cert-manager pods appear? If so are there anything in the pod logs? If the previous version doesn't work then it might be a configuration issue.

**Comment by cyrilghali** [comment]
No they didn't
But I did revert kubernetes to v1.26.3, and everything is up and running now @
I'll let you close this issue whenever you want

**Comment by onedr0p** [comment]
cert-manager pushed a new version which hopefully fixes this.

I've merged both commits and we will see if anything pops up.

**Comment by adampetrovic** [comment]
Hi, new user here.

I'm running v1.27.2 on Ubuntu 22.04.4 LTS with the latest HEAD of this template.

After setting up the cluster, when I run `task cluster:resources` I get the same error as @cyrilghali 

```
error: the server doesn't have a resource type "certificates"
task: Failed to run task "cluster:resources": task: Failed to run task "cluster:certificates": exit status 1
```

Additionally:
```
➜ kubectl -n cert-manager describe hr cert-manager
Error from server (NotFound): namespaces "cert-manager" not found
```

Is the recommendation to downgrade to v1.26? I assumed this was fixed because the PR was merged

**Comment by onedr0p** [comment]
The Flux HR for cert manager would still show up even if the version didn't work on 1.27.x

I suspect there's more going on here besides the cert manager version because I've witnessed other people bootstrapping this just fine on the recent changes. Maybe try to walk thru the steps one more time to see if there's something you might have missed?

**Comment by adampetrovic** [comment]
Thanks, the issue was that my repo was private. Making it public allowed everything to install properly.
